name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: swa-prod
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build
        # If you need build-time envs, uncomment and add repo secrets:
        # env:
        #   VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        #   VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Verify build output
        run: |
          test -d dist || (echo "dist not found" && exit 1)
          ls -la dist

      - name: Deploy to Azure Static Web Apps (Production)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: dist   # upload the built files (fixes MIME issue)
