name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 👇 run at REPO ROOT (no working-directory)
      - name: Install
        run: npm ci

      # (optional) inject Vite env vars from repo secrets
      - name: Build
        run: npm run build
        # env:
        #   VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        #   VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      # Upload the built /dist to your SWA
      - name: Deploy to Azure Static Web Apps (Production)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: /          # 👈 repo root
          output_location: dist    # 👈 Vite output
          skip_app_build: true     # we've already built above
