name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:   # 👈 manual runs only from the Actions tab

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy (manual)
    steps:
      - uses: actions/checkout@v4
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_STONE_0B2EE2810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "my-react-app"
          api_location: ""
          output_location: "build"
